#ddev-generated
services:
  typesense:
    container_name: ddev-${DDEV_SITENAME}-typesense
    image: typesense/typesense:0.25.0
    networks: [default, ddev_default]
    restart: on-failure
    ports:
      - "8108:8108"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - typesense:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

volumes:
  typesense:
